### ISSUE TITLE
Tilpas til mobil

### ISSUE THREAD

**Issue by baffioso** [rezaga/kontrast#2]

**Comment by baffioso** [comment]
Efter mobil tilpasning kører den ikke rigtig på desktop. Man skal scrolle ned for at komme til input m.m.

**Comment by rezaga** [comment]
Har rettet det nu, havde skrevet forkert. Virker i devTool med den rettet. Måske guthub er lidt langsomme med update??

**Comment by rezaga** [comment]
Er rettet til nu og har den rigtige ‘scale’ fra 600px (mobiltelf.)
